<form class="form-inline" action="<?php echo  str_replace("\\", "/", dirname($_SERVER['SCRIPT_NAME']));?>">
	<legend>Rival</legend>
	<div class="control-group">
		<label class="control-label" for="inputEmail">Email</label>
		<div class="controls">
		   	 <input type="text" id="inputEmail" placeholder="Email">
		</div>
		<label class="control-label" for="inputEmail">Username</label>
		<div class="controls">
			<input class="span2" id="prependedInput" type="text" placeholder="Username">
		</div>
	</div>
	<legend>Your</legend>
	<div class="control-group">
		<label class="control-label" for="inputEmail">Email</label>
		<div class="controls">
		   	 <input type="text" id="inputEmail" placeholder="Email">
		</div>
		<label class="control-label" for="inputEmail">Username</label>
		<div class="controls">
			<input class="span2" id="prependedInput" type="text" placeholder="Username">
		</div>
	</div>

	<div class="control-group">
	  <div class="btn-group" data-toggle="buttons-radio">
	  	<img src="http://localhost/PvW/img/Zend/ Stein.png" class="btn btn-primary" name=" Stein">
	  	<img src="http://localhost/PvW/img/Zend/Schere.png" class="btn btn-primary" name="Schere">
	  	<img src="http://localhost/PvW/img/Zend/Papier.png" class="btn btn-primary" name="Papier"> 
	  	<img src="http://localhost/PvW/img/Zend/Echse.png" class="btn btn-primary" name="Echse"> 
	  	<img src="http://localhost/PvW/img/Zend/spock.png" class="btn btn-primary" name="Spock"> 
   	 </div>
   	</div>
   	 <button type="submit" class="btn">Submit</button>
</form>