
	<?php echo $hallo->user1." ".$hallo->email1 ?> <br>
	<?php echo $hallo->user2." ".$hallo->email2 ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('game',array('action'=>'fight',"hash"=>$hallo->hash)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
	<div class="control-group">
	  <div class="btn-group" data-toggle="buttons-radio">
	  	<img src="http://localhost/PvW/img/Zend/ Stein.png" class="btn btn-primary" name=" Stein">
	  	<img src="http://localhost/PvW/img/Zend/Schere.png" class="btn btn-primary" name="Schere">
	  	<img src="http://localhost/PvW/img/Zend/Papier.png" class="btn btn-primary" name="Papier"> 
	  	<img src="http://localhost/PvW/img/Zend/Echse.png" class="btn btn-primary" name="Echse"> 
	  	<img src="http://localhost/PvW/img/Zend/spock.png" class="btn btn-primary" name="Spock"> 
   	 </div>
   	</div>
<?php
echo $this->formRow($form->get('choice2'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();