<script type="text/javascript">
function reply_click(clicked_id)
{
   var  x= document.forms[0].choice2;
   x.value=clicked_id;
}
</script>
<div id="succes"></div>
<div id="div">
<h1>Your turn</h1>
<div>
<?php echo "Userdata: ".$hallo->user2.", ".$hallo->email2; ?> <br>
<?php echo "Your challenger: ".$hallo->user1; ?> <br>
<?php echo "His/Her message:<br>".$hallo->msg1; ?>
</div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('game',array('action'=>'fight',"hash"=>$hallo->hash)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('msg2'));
?>
	<div id = "weapons"></div>
	<div class="control-group">
	  <div class="btn-group" data-toggle="buttons-radio">
	  	<img src="../../img/Zend/Stein.png" class="btn btn-primary" name="Stein" id="1" onClick="Fight.reply_click(this.id)">
	  	<img src="../../img/Zend/Papier.png" class="btn btn-primary" name="Papier"id="2" onClick="Fight.reply_click(this.id)">
        <img src="../../img/Zend/Schere.png" class="btn btn-primary" name="Schere" id="3" onClick="Fight.reply_click(this.id)">
	  	<img src="../../img/Zend/spock.png" class="btn btn-primary" name="Spock"id="4" onClick="Fight.reply_click(this.id)">
        <img src="../../img/Zend/Echse.png" class="btn btn-primary" name="Echse" id="5" onClick="Fight.reply_click(this.id)"> 
   	 </div>
   	</div>
<?php
echo $this->formHidden($form->get('choice2'));
echo $this->formHidden($form->get('hash'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
