<h1>Highscore</h1>
The top <?php echo $limit; ?> player!
<table class="table table-hover">
	<thead>
    	<tr>
            <th>
            	#
            </th>
        	<th>
            	User
            </th>
            <th>
            	Victories
            </th>
        </tr>
    </thead>
	
    <tbody>
    	<?php
			$i = 0;
			foreach($highscore as $key => $value){ 
				$i++;
		?>
        	<tr>
            	<td>
                	<?php echo $i; ?>
                </td>
                <td>
        			<?php echo $key; ?>
        		</td>
                <td>
					<?php echo $value; ?>
                </td>
        <?php 
			};
		?>
    </tbody>
</table>