<script type="text/javascript">
function reply_click(clicked_id)
{
   var  x= document.forms[0].choice1;
   x.value=clicked_id;
  }
  
function onsubmittest()
{
	var returnval=true;
	var  form = document.forms[0];
  	if(form.user1.value===''){
		returnval=false;
		form.user1.parentNode.parentNode.setAttribute('class','control-group error');
		var s=form.user1.parentNode.parentNode.childNodes[0];
		s.innerHTML='Your username is missing';
	}else{
		form.user1.parentNode.setAttribute('class','');
		form.user1.parentNode.parentNode.childNodes[0]='';
	}
	if(form.user2.value===''){
		returnval=false;
		form.user2.parentNode.parentNode.setAttribute('class','control-group error');
		var s=form.user2.parentNode.parentNode.childNodes[0];
		s.innerHTML='Your opponents username missing';
	}else{
		form.user2.parentNode.setAttribute('class','');
		form.user2.parentNode.parentNode.childNodes[0]='';
	}
  	if(form.email1.value==='' || !checkEmailFormat(form.email1.value)){
		returnval=false;
	   	form.email1.parentNode.parentNode.setAttribute('class','control-group error');
	   	var s=form.email1.parentNode.parentNode.childNodes[0];
	   	s.innerHTML='Your email is missing';
	}else{
		form.email1.parentNode.setAttribute('class','');
		form.email1.parentNode.parentNode.childNodes[0]='';
	}
	if(form.email2.value===''  || !checkEmailFormat(form.email2.value)){
		returnval=false;
		form.email2.parentNode.parentNode.setAttribute('class','control-group error');
		var s=form.email2.parentNode.parentNode.childNodes[0];
		s.innerHTML='Your opponents email is missing';
	}else{
		form.email2.parentNode.setAttribute('class','');
		form.email2.parentNode.parentNode.childNodes[0]='';
	}
  	if(form.choice1.value==='' || form.choice1.value === null || form.choice1.value === undefined){
		returnval=false;
		var el = document.getElementById('weapons');
		el.innerHTML='Please select a weapon!';
	}
   return returnval;
}


  function checkEmailFormat(email){

	  if(email.indexOf("@") === -1){
	  return false;
	  }
	  else{
	  email = email.substring(email.indexOf("@") + 1);
	  if(email.indexOf(".") === -1){
	  return false;
	  }
	  return true;
	  }
  };
</script>
<div id="succes"></div>
<h1>New Game</h1>

Fill in the fields, chose a weapon and start the game!

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('game'));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
?>
<div><label></label>
<?php 
echo $this->formRow($form->get('user1'));
?>
</div>
<div><label></label>
<?php 
echo $this->formRow($form->get('email1'));
?>
</div>
<div><label></label>
<?php
echo $this->formRow($form->get('user2'));
?>
</div>
<div><label></label>
<?php 
echo $this->formRow($form->get('email2'));
?>
</div>
	<div id = "weapons"></div>
	<div class="control-group">
	  <div class="btn-group" data-toggle="buttons-radio">
	  	<img src="../../img/Zend/Stein.png" class="btn btn-primary" name="Stein"  id="1" onClick="reply_click(this.id)">
	  	<img src="../../img/Zend/Papier.png" class="btn btn-primary" name="Papier" id="2" onClick="reply_click(this.id)">
        <img src="../../img/Zend/Schere.png" class="btn btn-primary" name="Schere" id="3" onClick="reply_click(this.id)">
	  	<img src="../../img/Zend/spock.png" class="btn btn-primary" name="Spock" id="4" onClick="reply_click(this.id)">
        <img src="../../img/Zend/Echse.png" class="btn btn-primary" name="Echse" id="5" onClick="reply_click(this.id)"> 
   	 </div>
   	</div>
<?php
echo $this->formHidden($form->get('choice1'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
