<div id="intro">
<h1>Rock-paper-scissors-lizard-Spock</h1>
<h2>The Game</h2>
Rock-paper-scissors-lizard-Spock is a five-gesture expansion of the classic selection method game rock-paper-scissors. It operates on the same basic principle, but includes two additional weapons: the lizard (formedby the hand as a sock-puppet-like mouth) and Spock (formed by the Star Trek Vulcan salute). This reduces the chances of a round ending in a tie. The game was invented by Sam Kass with Karen Bryla, as "Rock Paper Scissors Spock Lizard".<br />
The game was mentioned in three episodes of The Big Bang Theory. According to an interview with Kass, the series producers did not ask for permission to use the game, but he was later referenced in an episode in the fifth season. It has been used to understand the transitivity of climate change policy choice.

<h2>The Rules</h2>

The rules of Rock-paper-scissors-lizard-Spock are:
<ul>
    <li>
    	Scissors cut paper
    </li>
    <li>
    	Paper covers rock
    </li>
    <li>
    	Rock crushes lizard
    </li>
    <li>
    	Lizard poisons Spock
    </li>
    <li>
    	Spock smashes (or melts) scissors
    </li>
    <li>
    	Scissors decapitate lizard
    </li>
    <li>
    	Lizard eats paper
    </li>
    <li>
    	Paper disproves Spock
    </li>
    <li>
    	Spock vaporizes rock
    </li>
    <li>
    	Rock breaks scissors
    </li>
</ul>
</div>
<div id="highscore">
    <h1>Highscore</h1>
    
    <div id="table">
    
    </div>
</div>
<div id="game">

</div>
<div id="feedback">

</div>